update the github action file

diff --git a/.github/workflows/all_tests.yml b/.github/workflows/all_tests.yml
--- a/.github/workflows/all_tests.yml
+++ b/.github/workflows/all_tests.yml
@@ -23,30 +23,36 @@ on:
 # The whole action can contain sub-items called jobs
 # Jobs are run separately and will spin up a new build machine for each sub-item
 jobs:
-  build_tests:
+  Unbeatable_Mode:
     runs-on: ubuntu-latest
     steps:
       # Usually this is always needed
       - uses: actions/checkout@v2
 
       # Runs a set of commands using the runners shell
-      - name: Build Tests
+      - name: Running Test
         run:
           |
-          gcc -o bin/test/all_tests_run test/run_testing.c test/unit/unbeatable_mode/unbeatable_mode_game_simulation.c src/game_play/game_checkers.c src/game_play/user_turn.c src/game_play/game_play.c src/computer_turn/unbeatable_mode.c src/computer_turn/normal_mode.c src/computer_turn/computer_moves.c src/computer_turn/computer_turn.c src/common/graphic.c src/common/err.c test/unit/unbeatable_mode/user_choices_samples.c
-          bin/test/./all_tests_run > test_output.txt
+          gcc -o bin/test/unit/unbeatable_mode_game_simulation test/unit/unbeatable_mode/unbeatable_mode_game_simulation.c src/game_play/game_checkers.c src/game_play/user_turn.c src/game_play/game_play.c src/computer_turn/unbeatable_mode.c src/computer_turn/normal_mode.c src/computer_turn/computer_moves.c src/computer_turn/computer_turn.c src/common/graphic.c src/common/err.c
+          bin/test/unit/./unbeatable_mode_game_simulation > test_output.txt          
           if grep -q FAIL test_output.txt; then
             exit 1 # Exit with non-zero code to mark job as failed
           fi
 
-  # run_tests:
+  # Menu_Choice_One:
   #   runs-on: ubuntu-latest
   #   steps:
   #     # Usually this is always needed
   #     - uses: actions/checkout@v2
 
-#       - name: Check for test failures
-#          run: |
-#         if grep -q FAIL test_output.txt; then
-#           exit 1 # Exit with non-zero code to mark job as failed
-#         fi
+  #     # Runs a set of commands using the runners shell
+  #     - name: Running Test
+  #       run:
+  #         |
+
+  # THE RUN SYNTAX TO RUN ALL THE TEST AT ONCE
+  # gcc -o bin/test/all_tests_run test/run_testing.c test/unit/unbeatable_mode/unbeatable_mode_game_simulation.c src/game_play/game_checkers.c src/game_play/user_turn.c src/game_play/game_play.c src/computer_turn/unbeatable_mode.c src/computer_turn/normal_mode.c src/computer_turn/computer_moves.c src/computer_turn/computer_turn.c src/common/graphic.c src/common/err.c test/unit/unbeatable_mode/user_choices_samples.c
+  # bin/test/./all_tests_run > test_output.txt
+  # if grep -q FAIL test_output.txt; then
+  #   exit 1 # Exit with non-zero code to mark job as failed
+  # fi
