update github actions

diff --git a/.github/workflows/unit_tests.yml b/.github/workflows/unit_tests.yml
--- a/.github/workflows/unit_tests.yml
+++ b/.github/workflows/unit_tests.yml
@@ -31,17 +31,18 @@ jobs:
       - name: Running Test
         run:
           |
-          gcc -o bin/test/helper/user_choices_samples test/unit/unbeatable_mode/user_choices_samples.c
-          bin/test/helper/./user_choices_samples
           gcc -o bin/test/unit/unbeatable_mode_game_simulation test/unit/unbeatable_mode/unbeatable_mode_game_simulation.c src/game_play/game_checkers.c src/game_play/user_turn.c src/game_play/game_play.c src/computer_turn/unbeatable_mode.c src/computer_turn/normal_mode.c src/computer_turn/computer_moves.c src/computer_turn/computer_turn.c src/common/graphic.c src/common/err.c
           bin/test/unit/./unbeatable_mode_game_simulation > test_output.txt
           if grep -q FAIL test_output.txt; then
             exit 1 # Exit with non-zero code to mark job as failed
           fi
 
-  # THE RUN SYNTAX TO RUN ALL THE TESTS AT ONCE
-  # gcc -o bin/test/all_tests_run test/run_testing.c test/unit/unbeatable_mode/unbeatable_mode_game_simulation.c src/game_play/game_checkers.c src/game_play/user_turn.c src/game_play/game_play.c src/computer_turn/unbeatable_mode.c src/computer_turn/normal_mode.c src/computer_turn/computer_moves.c src/computer_turn/computer_turn.c src/common/graphic.c src/common/err.c test/unit/unbeatable_mode/user_choices_samples.c
-  # bin/test/./all_tests_run > test_output.txt
-  # if grep -q FAIL test_output.txt; then
-  #   exit 1 # Exit with non-zero code to mark job as failed
-  # fi
+# gcc -o bin/test/helper/user_choices_samples test/unit/unbeatable_mode/user_choices_samples.c
+# bin/test/helper/./user_choices_samples
+
+# THE RUN SYNTAX TO RUN ALL THE TESTS AT ONCE
+# gcc -o bin/test/all_tests_run test/run_testing.c test/unit/unbeatable_mode/unbeatable_mode_game_simulation.c src/game_play/game_checkers.c src/game_play/user_turn.c src/game_play/game_play.c src/computer_turn/unbeatable_mode.c src/computer_turn/normal_mode.c src/computer_turn/computer_moves.c src/computer_turn/computer_turn.c src/common/graphic.c src/common/err.c test/unit/unbeatable_mode/user_choices_samples.c
+# bin/test/./all_tests_run > test_output.txt
+# if grep -q FAIL test_output.txt; then
+#   exit 1 # Exit with non-zero code to mark job as failed
+# fi
