update github actions for unit testing

diff --git a/.github/workflows/unit_tests.yml b/.github/workflows/unit_tests.yml
--- a/.github/workflows/unit_tests.yml
+++ b/.github/workflows/unit_tests.yml
@@ -30,7 +30,7 @@ jobs:
           gcc -o bin/test/helper/user_choices_samples test/unit/unbeatable_mode/user_choices_samples.c
           bin/test/helper/./user_choices_samples > test_output.txt
           if grep -q PASS test_output.txt; then
-            exit 0 # Exit with non-zero code to mark job as failed
+            exit 1 # Exit with non-zero code to mark job as failed
           fi
 
       - name: Running Tests
